FROM docker.elastic.co/elasticsearch/elasticsearch:6.7.1

#RUN bin/elasticsearch-plugin remove x-pack --purge
#RUN bin/elasticsearch-plugin list

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
